--- #YAML:1.0
name:               Catalyst-TraitFor-Model-DBIC-Schema-ResultRoles
version:            0.01
abstract:           Automatically applying Moose Roles to Result-Classes at BUILD time
author:
    - Lukas Thiemeier <lukas@thiemeier.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
