--- #YAML:1.0
name:               Catalyst-TraitFor-Model-DBIC-Schema-ResultRoles
version:            0.0102
abstract:           automatically applying Moose Roles do Catalyst::Model::DBIC::Schema - resultclasses
author:
    - Lukas Thiemeier <lukast@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  6.56
build_requires:
    Catalyst::Model::DBIC::Schema:  0.48
    Catalyst::Runtime:    5.80
    DBIx::Class:          0.08126
    Moose:                1.21
    MooseX::NonMoose:     0.17
    SQL::Translator:      0.11007
    Test::More:           0.96
requires:
    Module::Find:         0.10
    Moose::Role:          1.21
    Moose::Util:          1.21
    namespace::autoclean:  0.11
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
